const fs = require('fs');

const exercises = JSON.parse(fs.readFileSync('src/data/hasan_exercises.json', 'utf8'));

const translations = {
  // Common Phrases
  "Lie flat on your back": "Acuéstate boca arriba",
  "with your knees bent": "con las rodillas dobladas",
  "feet flat on the ground": "los pies apoyados en el suelo",
  "Place your hands behind your head": "Coloca las manos detrás de la cabeza",
  "with your elbows pointing outwards": "con los codos hacia afuera",
  "Engaging your abs": "Contrayendo los abdominales",
  "slowly lift your upper body": "levanta lentamente el torso",
  "off the ground": "del suelo",
  "curling forward": "inclinándote hacia adelante",
  "until your torso is at a 45-degree angle": "hasta que tu torso esté en un ángulo de 45 grados",
  "Pause for a moment": "Pausa un momento",
  "at the top": "en la parte superior",
  "slowly lower your upper body": "baja lentamente el torso",
  "back down to the starting position": "a la posición inicial",
  "Repeat for the desired number of repetitions": "Repite las veces necesarias",
  "Stand with your feet shoulder-width apart": "Párate con los pies al ancho de los hombros",
  "your arms extended straight down by your sides": "los brazos extendidos a los lados",
  "Keeping your back straight": "Manteniendo la espalda recta",
  "your core engaged": "el core activo",
  "slowly bend your torso to one side": "inclina lentamente el torso hacia un lado",
  "lowering your hand towards your knee": "bajando la mano hacia la rodilla",
  "at the bottom": "en la parte inferior",
  "return to the starting position": "regresa a la posición inicial",
  "Repeat on the other side": "Repite en el otro lado",
  "Continue alternating sides": "Continúa alternando lados",
  "Lift your legs off the ground": "Levanta las piernas del suelo",
  "bend your knees at a 90-degree angle": "dobla las rodillas en 90 grados",
  "Bring your right elbow towards your left knee": "Lleva el codo derecho a la rodilla izquierda",
  "while simultaneously straightening your right leg": "mientras estiras la pierna derecha",
  "Return to the starting position": "Regresa a la posición inicial",
  "repeat the movement on the opposite side": "repite el movimiento al otro lado",
  "bringing your left elbow towards your right knee": "llevando el codo izquierdo a la rodilla derecha",
  "while straightening your left leg": "mientras estiras la pierna izquierda",
  "Continue alternating sides in a pedaling motion": "Continúa alternando en movimiento de pedaleo",
  "Start on all fours": "Empieza a cuatro patas",
  "hands directly under your shoulders": "manos bajo los hombros",
  "knees directly under your hips": "rodillas bajo las caderas",
  "Extend one leg straight back": "Extiende una pierna hacia atrás",
  "keeping your knee bent and your foot flexed": "manteniendo la rodilla doblada",
  "Slowly lower your hips towards the ground": "Baja lentamente la cadera al suelo",
  "feeling a stretch in your quads": "sintiendo el estiramiento en los cuádriceps",
  "Hold this position for 20-30 seconds": "Mantén la posición 20-30 segundos",
  "Switch legs": "Cambia de pierna",
  "repeat the stretch on the other side": "repite el estiramiento al otro lado",
  "Extend your arms straight out to the sides": "Extiende los brazos hacia los lados",
  "parallel to the ground": "paralelo al suelo",
  "lift your shoulders off the ground": "levanta los hombros del suelo",
  "reach your right hand towards your right heel": "toca tu talón derecho con la mano derecha",
  "reaching your left hand towards your left heel": "tocando tu talón izquierdo con la mano izquierda",
  "Sit on the cable machine": "Siéntate en la máquina de cables",
  "Grasp the handles": "Sujeta los agarres",
  "with an overhand grip": "con agarre prono",
  "slightly wider than shoulder-width apart": "ligeramente más ancho que los hombros",
  "Lean back slightly": "Inclínate un poco hacia atrás",
  "pull the handles towards your chest": "tira de los agarres hacia el pecho",
  "squeezing your shoulder blades together": "juntando las escápulas",
  "at the peak of the movement": "en el punto máximo",
  "slowly release the handles": "suelta lentamente los agarres",
  "Sit on the ground": "Siéntate en el suelo",
  "with your legs extended in front of you": "con las piernas estiradas",
  "Lift one leg off the ground": "Levanta una pierna del suelo",
  "rotate your ankle in a circular motion": "gira el tobillo en círculos",
  "Perform the desired number of circles in one direction": "Haz los círculos necesarios en una dirección",
  "then switch to the other direction": "luego cambia de dirección",
  "Repeat with the other leg": "Repite con la otra pierna",
  "Start by hanging from a pull-up bar": "Cuelga de una barra de dominadas",
  "Engage your core": "Activa el core",
  "pull your shoulder blades down and back": "lleva las escápulas hacia abajo y atrás",
  "As you pull yourself up": "Al subir",
  "bend one arm and bring your elbow towards your side": "dobla un brazo llevando el codo al costado",
  "keeping the other arm straight": "manteniendo el otro brazo recto",
  "Continue pulling until your chin is above the bar": "Sigue subiendo hasta que la barbilla pase la barra",
  "your bent arm is fully flexed": "tu brazo doblado esté flexionado",
  "Lower yourself back down with control": "Baja con control",
  "straightening the bent arm": "estirando el brazo doblado",
  "Alternate sides with each repetition": "Alterna lados en cada repetición",
  "Start in a push-up position": "Empieza en posición de flexión",
  "Extend one arm straight out to the side": "Extiende un brazo hacia el lado",
  "Lower your body by bending your elbows": "Baja doblando los codos",
  "Push back up to the starting position": "Empuja de vuelta al inicio",
  "extending the opposite arm out to the side": "extendiendo el brazo opuesto al lado",
  "Hang from a pull-up bar with your arms fully extended": "Cuelga de la barra con brazos estirados",
  "knees bent at a 90-degree angle": "rodillas dobladas a 90 grados",
  "lift your knees towards your chest": "lleva las rodillas al pecho",
  "bringing them as close to your elbows as possible": "lo más cerca posible de los codos",
  "Slowly lower your legs back down to the starting position": "Baja las piernas lentamente al inicio",
  "your legs straight down": "las piernas estiradas hacia abajo",
  "lift your legs up in front of you": "levanta las piernas frente a ti",
  "until they are parallel to the ground": "hasta que estén paralelas al suelo",
  "Hold for a moment at the top": "Mantén un momento arriba",
  "slowly lower your legs": "baja las piernas lentamente",
  "with your arms by your sides": "con los brazos a los lados",
  "Place your hands under your glutes for support": "Manos bajo los glúteos para apoyo",
  "Raise your legs until they are perpendicular to the ground": "Sube las piernas hasta que estén verticales",
  "Lower your legs back down": "Baja las piernas",
  "Simultaneously, throw your legs down towards the ground": "Lanza las piernas hacia el suelo",
  "keeping them straight": "manteniéndolas estiradas",
  "Raise your legs back up": "Sube las piernas de nuevo",
  
  // Nombres comunes
  "3/4 sit-up": "Abdominal 3/4",
  "45° side bend": "Inclinación lateral 45°",
  "air bike": "Bicicleta abdominal",
  "all fours squad stretch": "Estiramiento de cuádriceps a gatas",
  "alternate heel touchers": "Toques de talón alternos",
  "alternate lateral pulldown": "Jalón lateral alterno",
  "ankle circles": "Círculos de tobillo",
  "archer pull up": "Dominada de arquero",
  "archer push up": "Flexión de arquero",
  "arm slingers hanging bent knee legs": "Elevación de rodillas colgado",
  "arm slingers hanging straight legs": "Elevación de piernas colgado",
  "arms apart circular toe touch (male)": "Toque de puntas circular",
  "arms overhead full sit-up (male)": "Abdominal completo brazos arriba",
  "assisted chest dip (kneeling)": "Fondos de pecho asistidos",
  "assisted hanging knee raise": "Elevación de rodillas asistida",
  "assisted hanging knee raise with throw down": "Elevación de rodillas con empuje",
  "assisted lying calves stretch": "Estiramiento de gemelos asistido",
  "assisted lying glutes stretch": "Estiramiento de glúteos asistido",
  "assisted lying gluteus and piriformis stretch": "Estiramiento de piramidal asistido",
  "assisted lying leg raise with lateral throw down": "Elevación de piernas con empuje lateral",
  "assisted lying leg raise with throw down": "Elevación de piernas con empuje",
  "back and hip stretch": "Estiramiento de espalda y cadera",
  "back lever": "Back lever",
  "back ward pec deck fly": "Contractora de pecho inversa",
  "backward abdominal stretch": "Estiramiento abdominal",
  "backward medicine ball throw": "Lanzamiento de balón medicinal atrás",
  "band alternating biceps curl": "Curl de bíceps con banda alterno",
  "band assisted pull up": "Dominada asistida con banda",
  "band assisted tip toe calf raise": "Elevación de talones con banda",
  "band bench press": "Press de banca con banda",
  "band biceps curl": "Curl de bíceps con banda",
  "band close-grip pulldown": "Jalón al pecho agarre cerrado con banda",
  "band concentration curl": "Curl concentrado con banda",
  "band hip adductions": "Aducción de cadera con banda",
  "band kneeling one arm pulldown": "Jalón a una mano con banda arrodillado",
  "band lying hip internal rotation": "Rotación interna de cadera con banda",
  "band one arm overhead triceps extension": "Extensión de tríceps tras nuca con banda",
  "band one arm twisting chest press": "Press de pecho con banda a una mano",
  "band seated leg extension": "Extensión de piernas sentado con banda",
  "band seated row": "Remo sentado con banda",
  "band standing back leg raise": "Elevación de pierna atrás con banda",
  "band standing hip flexion": "Flexión de cadera con banda",
  "band standing leg extension": "Extensión de pierna de pie con banda",
  "barbell bench press": "Press de banca con barra",
  "barbell bicep curl": "Curl de bíceps con barra",
  "barbell deadlift": "Peso muerto con barra",
  "barbell squat": "Sentadilla con barra",
  "bodyweight crunch": "Crunch abdominal",
  "bodyweight pushup": "Flexión clásica",
  "bodyweight squat": "Sentadilla clásica",
  "burpee": "Burpee",
  "calp push up": "Flexión con palmada",
  "clap push up": "Flexión con palmada",
  "crunch floor": "Abdominales en suelo",
  "drop jump squat": "Sentadilla con salto",
  "front plank": "Plancha frontal",
  "glute bridge": "Puente de glúteo",
  "handstand push up": "Flexión de pino",
  "high knee": "Rodillas altas",
  "jumping jack": "Jumping jack",
  "lunge": "Zancada",
  "mountain climber": "Escalador",
  "muscle up": "Muscle up",
  "one arm push up": "Flexión a una mano",
  "pistol squat": "Sentadilla pistola",
  "plank": "Plancha",
  "pull up": "Dominada",
  "push up": "Flexión",
  "reverse crunch": "Crunch inverso",
  "side plank": "Plancha lateral",
  "triceps dip": "Fondos de tríceps",
  "walking lunge": "Zancada caminando"
};

const translatedExercises = exercises.map(ex => {
  let nameEs = translations[ex.name_en] || translations[ex.name] || ex.name_es || ex.name;
  
  let instructionsEs = [];
  if (ex.instruction_steps && ex.instruction_steps.en) {
    instructionsEs = ex.instruction_steps.en.map(step => {
      let translatedStep = step;
      // Replace known phrases
      Object.keys(translations).forEach(phrase => {
        if (step.includes(phrase)) {
          translatedStep = translatedStep.replace(phrase, translations[phrase]);
        }
      });
      return translatedStep;
    });
  }

  return {
    ...ex,
    name_es: nameEs,
    instruction_steps: {
      ...ex.instruction_steps,
      es: instructionsEs.length > 0 ? instructionsEs : (ex.instruction_steps ? ex.instruction_steps.tr : []) // fallback
    }
  };
});

fs.writeFileSync('src/data/hasan_exercises.json', JSON.stringify(translatedExercises, null, 2));
console.log("Translation complete!");
